Prevent Overwriting of User's Attributes on Register (#897)
flarum/framework pull request #1033
Opened 2016-09-13 07:43 UTC by dav-is

I read through the entire SSO process and this is the only security issue I could even remotely find regarding to #897. This will prevent any of the user's attributes to be overwritten. For example, if a SSO provider neglected to verify emails.

2016-09-13 19:40 UTC, franzliedke commented on src/Core/Command/RegisterUserHandler.php
> +                if ($user->$k == '' || ! isset($user->$k)) {
Isn't this the same as `if (empty($user->$k)`?

2016-09-13 19:42 UTC, dav-is commented on src/Core/Command/RegisterUserHandler.php
> +                if ($user->$k == '' || ! isset($user->$k)) {
Well empty would return true for 0 or false

2016-09-13 19:45 UTC, franzliedke commented on src/Core/Command/RegisterUserHandler.php
> +                if ($user->$k == '' || ! isset($user->$k)) {
So does `== ''`, see https://3v4l.org/Z6cl0.

Please use `===` then. :)

2016-09-24 12:13 UTC, tobscure commented
Can you please give a more concrete example of exactly how this could be exploited to screw something up? I agree that there's probably an issue here, but I'm having trouble imagining what that might be, and the complexity of the `if ($user->$k === '' || ! isset($user->$k))` condition is setting off alarm bells for me.

2016-09-24 16:29 UTC, dav-is commented
A user's attribute for email_when _mentioned (just making this up) is set to `0`. This setting is set and has a value of false. Therefore, it should not be tampered with. `if (empty($user->$k))` would return true because the value is false, but we still don't want to allow our SSO to modify the set variable.

2016-10-04 19:55 UTC, luceos requested changes
the conditional can be shortened using an empty() function

2016-10-04 19:59 UTC, dav-is commented
@luceos Did you read my rational behind not using empty()?

2016-10-04 20:01 UTC, Luceos commented
I skipped your last comment, my apologies. Even more impressed 😄

2016-10-04 20:02 UTC, luceos approved these changes

2016-10-04 20:04 UTC, Luceos commented
@tobscure or @franzliedke either merge this or assign to a milestone please. After having done that please unassign both of you.

2017-02-03 17:51 UTC, merged

2017-02-03 17:51 UTC, franzliedke commented
Thanks for the PR! And your patience. ;)

2017-02-03 17:54 UTC, franzliedke commented
I [slightly tweaked the condition](https://github.com/flarum/core/commit/7c1b0bfcf2fccc361cc984375dcc6a6430216b3a) to a statement that signals the intent slightly better - at least in my opinion.

And damn, should have squashed this ;)

2017-02-03 17:55 UTC, franzliedke commented
@dav-is Oh, last thing: Do you think we need to do anything about unknown attributes, i.e. a provider trying to set attributes that we don't even support? (Although I think that should just be a no-op, i.e. not be written to the database anyway).