Add search form to 404 page
flarum/framework pull request #1907
Opened 2019-10-09 20:25 UTC by lsilvio

**Fixes #1305 **

**Changes proposed in this pull request:**
Implement search form on 404 page.

**Screenshot**
![image](https://user-images.githubusercontent.com/52821596/66517555-a1878600-eae3-11e9-9f7e-eb8e85d05e31.png)

**Confirmed**
- [ ] Frontend changes: tested on a local Flarum installation.

2019-10-27 15:27 UTC, dsevillamartin requested changes

2019-10-27 15:27 UTC, datitisev commented on views/error/not_found.blade.php
> +    <form class="form" method="GET" action="/">
We cannot use `/` here for the action as it won't work with subfolders.
And is there a reason why the `form` has a class? It's not used anywhere, and styles only come from the inline `style` tag.

```suggestion
    <form class="form" method="GET" action="{{ $app->url() }}">
```

2019-11-06 22:33 UTC, datitisev commented
Also - the button has styles that aren't shown in your screenshot... and that mess up the styling.

![image](https://user-images.githubusercontent.com/6401250/68343771-8cd6e780-00bb-11ea-93a6-050d7ec762ed.png)

2020-02-05 09:33 UTC, luceos commented
We probably should just merge this and fix the last few things on this, anyone up to tackle this?

2020-03-27 18:44 UTC, askvortsov1 commented
While this solves the issue, I would propose that we consider an alternative approach, such as https://github.com/flarum/core/issues/654#issuecomment-593487567.

2020-05-18 19:26 UTC, askvortsov1 commented
Considering a lack of activity and consensus on where exactly we want to take this, I'm going to close this PR for now (can always reopen later) as we already have a lot open, and this isn't a priority for beta 14. Discussion can continue in #1305 and #654

2020-05-18 19:26 UTC, closed without merging