Convert common time helpers to Typescript
flarum/framework pull request #2391
Opened 2020-10-14 19:00 UTC by lhsazevedo

See #2342

2020-10-22 23:10 UTC, askvortsov1 requested changes
This mostly makes sense, thanks!

2020-10-22 23:10 UTC, askvortsov1 commented on js/src/common/helpers/fullTime.tsx
> +import * as Mithrill from 'mithril';
Typo

2020-10-24 04:54 UTC, clarkwinkelmann reviewed
Why does one import uses `import * as dayjs from 'dayjs'; ` while the others use `import dayjs from 'dayjs'; ` ?

Do we actually want to import global variables or could we just type-hint them somewhere? Using the global variable instead of an import will save up on the file size, as webpack won't have to add the additional code that resolves each import.

2020-10-24 20:35 UTC, datitisev commented
@clarkwinkelmann We can test locally if the bundle size increases if they're just used for typings. Haven't done so myself yet.

2020-10-24 22:19 UTC, lhsazevedo commented on js/src/common/helpers/fullTime.tsx
> +import * as Mithrill from 'mithril';
Fixed

2020-10-24 22:41 UTC, lhsazevedo commented
I removed the `import * as dayjs` variant and now all three changed files use the default export

2020-10-25 05:28 UTC, askvortsov1 commented on js/src/common/helpers/fullTime.tsx
> +import * as Mithrill from 'mithril';
Thanks! :D

2020-10-25 05:29 UTC, askvortsov1 approved these changes
Looks good to me! I'm approving this as long as

> Do we actually want to import global variables or could we just type-hint them somewhere? Using the global variable instead of an import will save up on the file size, as webpack won't have to add the additional code that resolves each import.

doesn't prove to be an issue

2020-10-25 06:10 UTC, lhsazevedo commented
@askvortsov Thanks, I'll test this as soon as possible.

2020-10-25 23:49 UTC, lhsazevedo commented
## Test
So, apparently webpack doesn't inject the module resolving code on each module, but use a global one. [Here's the test i did](https://gist.github.com/lhsazevedo/a49c5962db67251313e0b22ebbed4d37).

## Flarum build
Heres `src/common/utils/humanTime.ts` unminified output:
```js
"use strict";
__webpack_require__.d(__webpack_exports__, "a", function() { return humanTime; });
var dayjs = __webpack_require__(28);
var dayjs_default = /*#__PURE__*/__webpack_require__.n(dayjs);
var dayjs_plugin_relativeTime = __webpack_require__(73);
var dayjs_plugin_relativeTime_default = /*#__PURE__*/__webpack_require__.n(dayjs_plugin_relativeTime);

function humanTime(time) {
  var d = dayjs_default()(time);
  var now = dayjs_default()();

  // ...
}
```

## Dayjs plugins
One thing we could optimize is, even not using directly, we need to import relativeTime dayjs plugin at `js/src/common/utils/humanTime.ts`. Without this import, typescript can't pick up tipes for the [fromNow()](https://github.com/flarum/core/blob/2ff46f5a2ebe2532f780f6e60a921beb41876d69/js/src/common/utils/humanTime.ts#L32) method and complains.
The code still works though, because relativeTime plugin is installed at `js/src/common/index.js`:

https://github.com/flarum/core/blob/2ff46f5a2ebe2532f780f6e60a921beb41876d69/js/src/common/index.js#L12-L16

We can avoid this import if we move this plugin installation process to a separated dayjs library module, something like:
```typescript
// js/src/common/lib/dayjs.ts

import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime)

export default dayjs


// js/src/common/utils/humanTime.ts

// no need import relativeTime from 'dayjs/plugin/relativeTime';
import dayjs from '../../common/lib/dayjs'
```
Should I open a new issue for this?

2020-10-26 15:28 UTC, askvortsov1 commented
> So, apparently webpack doesn't inject the module resolving code on each module, but use a global one. [Here's the test i did](https://gist.github.com/lhsazevedo/a49c5962db67251313e0b22ebbed4d37).

Thank you for testing this!



> We can avoid this import if we move this plugin installation process to a separated dayjs library module, something like:

Hmm I really like this idea! @clarkwinkelmann @rob006 could this also work for https://discuss.flarum.org/d/25196-beta-14-dayjs-translations?

2020-10-26 15:47 UTC, datitisev commented
@askvortsov1 It could technically work but the config files would need to use `flarum.core.compat['flarum/lib/dayjs']` to access it.

2020-10-28 01:11 UTC, lhsazevedo commented
It seems that it would be a more drastic change, and the code already works without it, so I created [a new issue](https://github.com/flarum/core/issues/2417) for this subject so that we can move forward here.

2020-10-29 16:49 UTC, clarkwinkelmann approved these changes
I'm triggered by the imports order ahah (`fullTime` imports dayjs first, while `humanTime` imports Mithril first :hear_no_evil: )

Looks good otherwise.

2020-10-29 23:17 UTC, lhsazevedo commented
@clarkwinkelmann Fixed following this rule: external imports first, internal last, both alphabetically sorted.

2020-10-30 22:20 UTC, tankerkiller125 approved these changes

2020-10-31 00:27 UTC, merged