fixed container bindings use of container
flarum/framework pull request #2807
Opened 2021-04-22 12:57 UTC by luceos

> No time to write the issue, someone 🙏 There's supposed to be an issue somewhere for this.

**Fixes #0000**

**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2021-04-22 15:56 UTC, askvortsov1 requested changes
Found one you missed

2021-04-22 15:56 UTC, askvortsov1 commented on src/User/UserServiceProvider.php
> +        User::setGate($container->makeWith(Access\Gate::class, ['policyClasses' => $this->container->make('flarum.policies')]));
Missed one

2021-04-22 15:56 UTC, askvortsov1 requested changes

2021-04-22 15:56 UTC, askvortsov1 commented on src/User/UserServiceProvider.php
> +        User::setGate($container->makeWith(Access\Gate::class, ['policyClasses' => $this->container->make('flarum.policies')]));
```suggestion
        User::setGate($container->makeWith(Access\Gate::class, ['policyClasses' => $this->container->make('flarum.policies')]));
```
```suggestion
        User::setGate($container->makeWith(Access\Gate::class, ['policyClasses' => $container->make('flarum.policies')]));
```

2021-04-29 18:27 UTC, askvortsov1 approved these changes

2021-04-29 19:05 UTC, tankerkiller125 approved these changes

2021-04-29 19:33 UTC, merged

2021-04-29 20:48 UTC, askvortsov1 commented
PArt of https://github.com/flarum/core/issues/2763