Add ability to set email confirmation state to false
flarum/framework pull request #2997
Opened 2021-07-31 23:30 UTC by davwheat

**Changes proposed in this pull request:**

Allows admins to set email confirmation state to `false`.

**Reviewers should focus on:**

Should we instead add a `deactivate` method to `User.php` and fire a deactivation event, similar to what we do for activation?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

2021-08-06 10:43 UTC, luceos commented
I see that User::activate fires an event, would it make sense to have a similar event (and perhaps method on User) for deactivation?

Other than that this PR looks fine.

2021-08-09 15:13 UTC, davwheat commented
Implemented both. We now have `User::deactivate` and a `Deactivated` event.

2021-08-14 22:50 UTC, askvortsov1 commented
I am not convinced of the use case for this. As mentioned over chat, I would be in favor of a general activation / deactivation mechanism where email confirmation is one factor, but until then, what's the use case for marking an email as not confirmed?

2021-09-03 18:03 UTC, luceos commented
I was reading through the changes and got confused by the fact that activation and deactivation relies on a column about email verification. To that extend I agree, for now we might keep this logic and extend or modify it later? Imo this logic almost warrants it's own database column `activated_at`?

2021-09-10 20:02 UTC, davwheat commented
I think we should add this for now, and then change the activation logic later.

2021-11-02 19:15 UTC, askvortsov1 commented
Very well, I think we can do this, but could we rename the methods to `confirmEmail` and `unconfirmEmail` (and deprecate `activate`)? Then the API would be consistent with the behavior we want to work towards in the future.

2021-11-08 21:44 UTC, askvortsov1 requested changes
Looking over this again, I would be happy to approve this if we changed the method names as described above.

2022-03-16 19:30 UTC, askvortsov1 commented
Hello, thank you for your pull request! In order to speed up future development, keep all work in one place, and take advantage of CI tools that can help us avoid breaking changes, we have moved all Flarum code to a single monorepo at [flarum/framework](https://github.com/flarum/framework). You can read more about this process [in our dev diary](https://discuss.flarum.org/d/29894-dev-diary-build-20/3). Unfortunately, pull requests can't be carried over to the monorepo, so we have to close all open pull requests. If this pull request is still relevant, please feel free to reopen it over on the monorepo. We apologize for the inconvenience, and hope you will consider contributing to Flarum again in the future.

2022-03-16 19:30 UTC, closed without merging