[A11Y] Replace invalid link elements with buttons
flarum/framework pull request #3021
Opened 2021-08-12 16:38 UTC by davwheat

**Changes proposed in this pull request:**

- Replace links with no or dead hrefs with `<button>` elements
- Add new `.Button--reset` class which removes all native styles from buttons

**Reviewers should focus on:**

Anywhere I've missed? Should the Link be removed from "dead" authors?

**Screenshot**

![image](https://user-images.githubusercontent.com/7406822/129234680-ac79647c-7420-42ee-802f-a024fc5baef0.png)

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

2021-08-14 19:11 UTC, askvortsov1 reviewed
To me, `reset` implies that it's using browser native button styling. Is there a convention behind this naming?

2021-08-14 20:16 UTC, SychO9 commented
I haven't reviewed yet, but we have `Button--link` and `Button--text`, don't one of these do the job ?

2021-08-14 21:36 UTC, davwheat commented
Unfortunately not. `Button--link` keeps the button padding, and `Button--text` results in incorrect vertical aligning and undesired underlining on hover/focus (which doesn't match the previous behaviour with `<a>` without `href` attributes.

We definitely don't want the underlining in some places (post scrubber for example), but other areas I'd be open to ("links" in modals).

2021-08-14 21:56 UTC, SychO9 commented
Ah I see, makes sense.

btw, I believe we can do `all: unset` here :D found out about it recently!

2021-09-20 21:53 UTC, askvortsov1 approved these changes

2021-10-16 13:26 UTC, dsevillamartin commented
Not tested the changes or really looked at CSS, mainly focused on JS. 
My thoughts are basically on cleaning this up rather than anything else -

We could potentially have a <`Component`/`Tag`> variable that switches between `Link` and `span` to avoid this code duplication. Don't know if that'd be better or worse - potentially create a separate component that chooses the tag (including `<Button>` reset for `onclick`)? 🤔 

That way it would avoid writing `Button Button--reset` every time (unless we explicitly want it) or handling falsy `href`/`onclick`'s, as the component would do that too.

2021-10-30 22:17 UTC, SychO9 reviewed
The `Button--reset` looks fine with the scrubber buttons, but odd with the rest.

2021-10-30 22:17 UTC, SychO9 commented on js/src/forum/components/PostMeta.js
> +        <Button className="Button Button--reset Dropdown-toggle" onclick={selectPermalink} data-toggle="dropdown">
the timestamp looks colored at all times, can we instead use `Button--text` here and just add a `vertical-align: bottom;` to `.Button--text` ? it's a lot more consistent.

2021-10-30 22:17 UTC, SychO9 commented on js/src/forum/components/LogInModal.js
> +            a: <Button class="Button Button--reset" onclick={this.signUp.bind(this)} />,
these look weird as well, colored with no effect on hover, the underline hovering effect of the link was nice.
perhaps we should add a new `Button--textlink` that would mimic an exact link?

2021-11-17 19:34 UTC, SychO9 requested changes
Already left a review 👼🏼

2022-03-16 19:30 UTC, askvortsov1 commented
Hello, thank you for your pull request! In order to speed up future development, keep all work in one place, and take advantage of CI tools that can help us avoid breaking changes, we have moved all Flarum code to a single monorepo at [flarum/framework](https://github.com/flarum/framework). You can read more about this process [in our dev diary](https://discuss.flarum.org/d/29894-dev-diary-build-20/3). Unfortunately, pull requests can't be carried over to the monorepo, so we have to close all open pull requests. If this pull request is still relevant, please feel free to reopen it over on the monorepo. We apologize for the inconvenience, and hope you will consider contributing to Flarum again in the future.

2022-03-16 19:30 UTC, closed without merging