Extract sortmap options to container
flarum/framework pull request #3254
Opened 2022-01-06 20:44 UTC by imorland

**Partially addresses #2955 **

**Changes proposed in this pull request:**
Make the backend sort options list a container binding so extensions can modify it

**Reviewers should focus on:**
I don't think we should go further for the moment (ie serializing to the frontend, etc) until https://github.com/flarum/core/pull/3133 is merged also. This change proposed here will at least allow extensions to properly add additional sort options

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2022-02-02 21:10 UTC, askvortsov1 commented
I agree with this idea in theory, but for v2.0 I'm hoping that this will be completely included in extenders, and therefore we'd need to uproot all extensions using this feature.

2022-02-07 10:25 UTC, luceos commented
@askvortsov1 upon reading this PR I was actually considering something else as well. Especially because I'm not a fan of "ioc binding all the things" anymore. What did you have in mind, where would you store the sorting?

2022-02-07 18:49 UTC, askvortsov1 commented
> @askvortsov1 upon reading this PR I was actually considering something else as well. Especially because I'm not a fan of "ioc binding all the things" anymore. What did you have in mind, where would you store the sorting?

It would probably still be in the ioc, which isn't a bad thing IMO since it is global-state site configuration. But the IOC ideally wouldn't be the public API way of intracting with it.

2022-02-21 10:51 UTC, luceos commented
I'd personally see every related to sort inside one class responsible per model. So the `Discussion` model having a `DiscussionSearchParams` which includes the logic for the sort mapping as well. 

I would be okay with merging this in as long as an issue is attached to v2.0 as a reminder to remove/review this. Are we okay to move forward with this @askvortsov1 ?

2022-03-10 00:56 UTC, askvortsov1 requested changes

2022-03-10 00:56 UTC, askvortsov1 commented on src/Extend/Sortmap.php
> +class Sortmap implements ExtenderInterface
Let's drop this class for now until we figure out a cleaner way to generalize this for all models. Other than that, good to go IMO.

2022-03-10 00:56 UTC, askvortsov1 commented on src/Forum/Content/Index.php
> +        $sortMap = resolve('flarum.forum.sortmap');
Is there no way we can inject this in the constructor?

2022-03-16 19:35 UTC, askvortsov1 commented
Hello, thank you for your pull request! In order to speed up future development, keep all work in one place, and take advantage of CI tools that can help us avoid breaking changes, we have moved all Flarum code to a single monorepo at [flarum/framework](https://github.com/flarum/framework). You can read more about this process [in our dev diary](https://discuss.flarum.org/d/29894-dev-diary-build-20/3). Unfortunately, pull requests can't be carried over to the monorepo, so we have to close all open pull requests. If this pull request is still relevant, please feel free to reopen it over on the monorepo. We apologize for the inconvenience, and hope you will consider contributing to Flarum again in the future.

2022-03-16 19:35 UTC, closed without merging