Assorted Typing Fixes
flarum/framework pull request #3348
Opened 2022-03-12 07:28 UTC by askvortsov1

Moving one step closer to having all the hundreds of CI jobs on this monorepo be green.

2022-03-16 16:23 UTC, SychO9 approved these changes
Amazing to see this!

Wouldn't have been fun across multiple repositories >.>

Looks like the diff shows dist files despite `.gitattributes` files instructing against, it seems like only a root level `.gitattributes` is taken into consideration so we'll probably want to add one.

Other than that, all looks good to me! Thanks for the well-split commits.

2022-03-17 00:25 UTC, davwheat requested changes
Most of these are just using `import type` instead of `import` to make certain that we don't accidentally use the imports for anything except typing.

Another thing to note is that we should *really* be marking view method return types as `Mithril.Children` rather than the automatic `JSX.Element` since that doesn't allow extends/overrides to return things like `null`, strings, numbers or arrays as fragments.

Thank you for your hard work on this 🤗🥰

2022-03-17 00:25 UTC, davwheat commented on extensions/akismet/js/src/forum/index.ts
> +import Mithril from 'mithril';
```suggestion
import type Mithril from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on extensions/flags/js/src/forum/index.ts
> +import Post from 'flarum/common/models/Post';
I think this should be at the top of the file instead, for clarity.

2022-03-17 00:25 UTC, davwheat commented on extensions/flags/js/src/forum/models/Flag.ts
> +import Post from 'flarum/common/models/Post';
```suggestion
import type Post from 'flarum/common/models/Post';
```

2022-03-17 00:25 UTC, davwheat commented on extensions/flags/js/src/forum/models/Flag.ts
> +import User from 'flarum/common/models/User';
```suggestion
import type User from 'flarum/common/models/User';
```

2022-03-17 00:25 UTC, davwheat commented on extensions/pusher/js/src/forum/index.ts
> +import { Children } from 'mithril';
```suggestion
import type { Children } from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on extensions/pusher/js/src/forum/index.ts
> +import Tag from 'flarum/tags/common/models/Tag';
```suggestion
import type Tag from 'flarum/tags/common/models/Tag';
```

2022-03-17 00:25 UTC, davwheat commented on extensions/tags/js/dist-typings/@types/shims.d.ts
> +import Tag from "../common/models/Tag";
```suggestion
import type Tag from "../common/models/Tag";
```

2022-03-17 00:25 UTC, davwheat commented on extensions/tags/js/dist-typings/@types/shims.d.ts
> +import TagListState from "../forum/states/TagListState";
```suggestion
import type TagListState from "../forum/states/TagListState";
```

2022-03-17 00:25 UTC, davwheat commented on extensions/tags/js/src/@types/shims.d.ts
> +import Tag from "../common/models/Tag";
```suggestion
import type Tag from "../common/models/Tag";
```

2022-03-17 00:25 UTC, davwheat commented on extensions/tags/js/src/@types/shims.d.ts
> +import TagListState from "../forum/states/TagListState";
```suggestion
import type TagListState from "../forum/states/TagListState";
```

2022-03-17 00:25 UTC, davwheat commented on extensions/tags/js/src/common/models/Tag.ts
> +import Discussion from 'flarum/common/models/Discussion';
```suggestion
import type Discussion from 'flarum/common/models/Discussion';
```

2022-03-17 00:25 UTC, davwheat commented on extensions/tags/js/src/forum/states/TagListState.ts
> +import Tag from "../../common/models/Tag";
```suggestion
import type Tag from "../../common/models/Tag";
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/dist-typings/admin/AdminApplication.d.ts
> +import { AdminRoutes } from './routes';
```suggestion
import type { AdminRoutes } from './routes';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/dist-typings/admin/components/HeaderPrimary.d.ts
> +    view(): JSX.Element;
All of these should really be `Mithril.Children` instead (return type manually defined in the method declaration).

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/admin/components/DashboardPage.tsx
> +import { Children } from 'mithril';
```suggestion
import type { Children } from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/admin/components/DashboardWidget.tsx
> +import { Children, Vnode } from 'mithril';
```suggestion
import type { Children, Vnode } from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/ForumApplication.ts
> +import NotificationModel from '../common/models/Notification';
```suggestion
import type NotificationModel from '../common/models/Notification';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/ForumApplication.ts
> +import PostModel from '../common/models/Post';
```suggestion
import type PostModel from '../common/models/Post';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/ForumApplication.ts
>  import Discussion from '../common/models/Discussion';
I know this wasn't part of your changes, but it shouldn't hurt.

```suggestion
import type Discussion from '../common/models/Discussion';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/DiscussionListItem.tsx
> +import Discussion from '../../common/models/Discussion';
```suggestion
import type Discussion from '../../common/models/Discussion';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/DiscussionListItem.tsx
> +import Mithril from 'mithril';
```suggestion
import type Mithril from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/DiscussionListItem.tsx
> +import { DiscussionListParams } from '../states/DiscussionListState';
```suggestion
import type { DiscussionListParams } from '../states/DiscussionListState';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/DiscussionRenamedNotification.tsx
> +import Discussion from '../../common/models/Discussion';
```suggestion
import type Discussion from '../../common/models/Discussion';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/DiscussionRenamedNotification.tsx
> +    return '';
Does it make more sense to return `null` instead?

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/Notification.tsx
> +import NotificationModel from '../../common/models/Notification';
```suggestion
import type NotificationModel from '../../common/models/Notification';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/Notification.tsx
> +import Mithril from 'mithril';
```suggestion
import type Mithril from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/Post.tsx
> +import PostModel from '../../common/models/Post';
```suggestion
import type PostModel from '../../common/models/Post';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/components/Post.tsx
> +import Mithril from 'mithril';
```suggestion
import type Mithril from 'mithril';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/routes.ts
>  import Post from '../common/models/Post';
```suggestion
import type Post from '../common/models/Post';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/routes.ts
>  import User from '../common/models/User';
```suggestion
import type User from '../common/models/User';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/states/PostStreamState.ts
> +import Discussion from '../../common/models/Discussion';
```suggestion
import type Discussion from '../../common/models/Discussion';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/states/PostStreamState.ts
> +import Post from '../../common/models/Post';
```suggestion
import type Post from '../../common/models/Post';
```

2022-03-17 00:25 UTC, davwheat commented on framework/core/js/src/forum/states/PostStreamState.ts
> +  ['constructor']: typeof PostStreamState;
Hah, clever!

2022-03-18 18:13 UTC, askvortsov1 commented on framework/core/js/src/forum/states/PostStreamState.ts
> +  ['constructor']: typeof PostStreamState;
All credit goes to the one guy on stack overflow :wink:

2022-03-23 10:14 UTC, davwheat approved these changes

2022-03-23 15:43 UTC, merged