fix: don't duplicate path in URL to post on subdirectory installs.
flarum/framework pull request #3354
Opened 2022-03-19 21:11 UTC by askvortsov1

2022-03-23 07:30 UTC, luceos commented
Feels like this issue solves **one** instance of a problem, a problem that can cascade into other areas including 3rd party extensions. What is exactly the cause? Is baseUrl sometimes the domain + path and sometimes just the path?

2022-03-23 14:53 UTC, dsevillamartin commented
@luceos `baseUrl` has the URL in `config.php`, so it will always have the subfolder if there is one. `app.route` will return an URL with the subfolder as well because it is needed for navigation to the correct page (`/subfolder/d/...`).

2022-03-23 15:00 UTC, davwheat requested changes

2022-03-23 15:00 UTC, davwheat commented on framework/core/js/src/forum/components/PostMeta.js
> +    return URL(app.forum.attribute('baseUrl')).hostname + app.route.post(post);
This will not keep URLs which contain ports, nor the protocol. We should use `.origin` instead.


```suggestion
    return new URL(app.forum.attribute('baseUrl')).origin + app.route.post(post);
```

2022-04-06 13:05 UTC, SychO9 approved these changes

2022-04-23 11:22 UTC, davwheat approved these changes

2022-04-23 14:23 UTC, merged