fix(core): don't pass null to functions where that's deprecated
flarum/framework pull request #3405
Opened 2022-04-21 21:23 UTC by askvortsov1

Should fix issues such as https://github.com/flarum/framework/runs/6119368985?check_suite_focus=true

2022-04-21 21:45 UTC, davwheat requested changes

2022-04-21 21:45 UTC, davwheat commented on framework/core/src/Http/AccessToken.php
> +            $this->last_user_agent = $agent !== null ? substr($agent, 0, 255) : null;
This results in different behaviour. Passing `null` to `substr()` will default to an empty string, but this falls back to null.

```suggestion
            $this->last_user_agent = ? substr($agent ?? "", 0, 255);
```

2022-04-21 22:25 UTC, davwheat commented on framework/core/src/Http/AccessToken.php
> +            $this->last_user_agent = ? substr($agent ?? '', 0, 255);
Sorry, my bad. Mobile!

```suggestion
            $this->last_user_agent = substr($agent ?? '', 0, 255);
```

2022-04-22 08:34 UTC, davwheat approved these changes

2022-04-22 10:42 UTC, SychO9 approved these changes

2022-04-22 12:02 UTC, tankerkiller125 approved these changes

2022-04-24 20:26 UTC, merged