Make it possible to reply (or create a discussion) with another post type than `comment`
flarum/framework pull request #3421
Opened 2022-05-12 15:34 UTC by iPurpl3x

**Changes proposed in this pull request:**
Nothing breaking, just added the possibility to handle a `type` attribute coming from an API call to either create a discussion or reply to one. When the `type` attribute is provided, the according post model is used to create the post. This makes it possible to start a discussion with a post that is not of type `comment`. 

Obviously the custom type need to be registered using the `Post` extender and the `reply()` method needs to be implemented with the same parameters as for the `reply()` method of the `CommentPost` model.

When no `type` is found, the post will be considered as a `comment` by default.

**Reviewers should focus on:**
Nothing is broken, the new ability to create a post with a custom type works as expected.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

2022-05-12 18:07 UTC, askvortsov1 requested changes
I like the idea in theory, but I think we might need a bit more complicated approach, due to reasons I point out in comments below.

2022-05-12 18:07 UTC, askvortsov1 commented on framework/core/src/Post/Command/PostReplyHandler.php
> +        $postModel = Post::getModels()[$type];
I wonder if this should be tied to some security / permissions model? I could envision someone using a custom API client to create post types that should only be allowed by the system.

2022-05-12 18:07 UTC, askvortsov1 commented on framework/core/src/Post/Command/PostReplyHandler.php
> +        $post = $postModel::reply(
Not all post models will have this interface for the `reply` method, so this isn't structurally sound.

2022-05-14 17:40 UTC, clarkwinkelmann requested changes
At the very least it needs more error handing.

Line 86 will throw a PHP array access warning if the key doesn't exist.

Line 91 will throw a 500 error if the method doesn't exist. Checking for an interface could be a solution.

I think both permission and validation could be achieved with a single interface. The interface could be called something like "text repliable (via API?)" But interface cannot be for static methods if I remember correctly? That's not a deal breaker, the method could be moved to non-static and the model instantiated before call.

I do have some concerns for other extensions as well. If an extension extends the `Post\Saving` event. would it be supposed to handle those posts like if they were instances of `CommentPost` ? Since many extensions have logic explicitely for `CommentPost`, setting a different type here might bypass a lot of logic from other extensions, which could be intentional but also not, depending on the use case.

This looks like something an extension could implement relatively easily, use `Saving` event and look for a specific `type` value in payload, otherwise ignore. Does having it core really make anything easier? If any of those special types has special handling, the `Saving` event will have to be used anyway.

2022-11-07 10:20 UTC, luceos commented
Moved to a roadmap, continuous effort task. We have some ideas on how to approach this, but we first need to decide on the best path forward and then draft a technical plan for implementation.

2022-11-07 10:20 UTC, closed without merging