Make unread notifications method public
flarum/framework pull request #3424
Opened 2022-05-14 14:43 UTC by BurnNoticeSpy

Makes the notifications method public in `framework/core/src/User/User.php`

2022-05-15 07:37 UTC, luceos approved these changes

2022-05-19 12:08 UTC, tankerkiller125 approved these changes

2022-05-26 17:36 UTC, imorland approved these changes

2022-05-26 18:33 UTC, davwheat requested changes
I am not comfortable merging this with the current caching system present on the method.

2022-06-05 00:19 UTC, BurnNoticeSpy commented
So is this caching style done elsewhere? Can it be handled separately from this PR?

Thoughts on the danger of making this public from the other reviewers?

2022-07-05 10:08 UTC, luceos commented
I think I've come to agree this stance and to prevent this PR from dragging along, we should discuss options inside an issue before we move forward with a solution.

If you're up for taking the lead on this discussion @BurnNoticeSpy feel free to open an issue on this repository.

Thanks for the effort by the way, this is not about you or your code. This is about guaranteeing stability, security and compatibility in extensibility which we'll be responsible to maintain moving forward.

2022-07-05 10:08 UTC, closed without merging