Feature: Stackable modals and removed bootstrap dialogs
flarum/framework pull request #3456
Opened 2022-06-10 23:23 UTC by jaspervriends

**Changes proposed in this pull request:**
In this PR I've worked on making it possible to have multiple dialogs opened at the same time and make them stackable. I have partly used code of #3246 and altered it. It also removed the bootstrap modal dependency.

However, I did not proceed using the native HTML Dialog element for this PR due to lack of animations (for example, the backdrop is not animatable) and responsiveness with the interface.

A third `stackModal` parameter has been added to the `app.modal.show` function which is a boolean and defaults to `false`. This means that all already existing modals will keep their intended behaviour.

**Reviewers should focus on:**
- Current modals are opening and closing as intended
- Stacking multiple modals works
- Responsiveness is still good

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

2022-06-11 03:30 UTC, davwheat reviewed
Just some comments so far. Haven't had time to properly review yet.

2022-06-11 03:30 UTC, davwheat commented on framework/core/js/src/common/components/ModalManager.tsx
> +      const zIndex = 9999 + modal.key;
Is this needed? Elements with the same zIndex should stack as per normal DOM hierarchy rules, where the last element is on top.

If we are going to do it this way, we should use the CSS variable for modal z-index and either:

1. Provide an custom attribute, such as `--modal-number`, then use `calc()` to set the z-index

2. Fetch the value of the modal z-index attribute on the `::root` selector and use that instead of a hardcoded value.

I expect number 1 will be easier.

2022-06-11 03:30 UTC, davwheat commented on framework/core/js/src/common/components/ModalManager.tsx
> +        <div className="ModalManager modal" modal-key={modal.key} style={{ zIndex }}>
I would prefer to use `data-modal-key`.

2022-06-11 03:30 UTC, davwheat commented on framework/core/js/src/common/components/ModalManager.tsx
> +  private get dialogElement(): HTMLElement {
Could we rename this to more suitable match the doc block?


```suggestion
  private get activeDialogElement(): HTMLElement {
```

2022-06-11 03:30 UTC, davwheat commented on framework/core/js/src/common/components/ModalManager.tsx
> +  private get backdropElement(): HTMLElement {
```suggestion
  private get activeBackdropElement(): HTMLElement {
```

2022-06-11 03:30 UTC, davwheat commented on framework/core/js/src/common/states/ModalManagerState.ts
> +  show(componentClass: UnsafeModalClass, attrs: Record<string, unknown> = {}, stackModal: Boolean = false): void {
We should use `boolean` primitive rather than the `Boolean` object.

```suggestion
  show(componentClass: UnsafeModalClass, attrs: Record<string, unknown> = {}, stackModal: boolean = false): void {
```

2022-06-11 03:30 UTC, davwheat commented on framework/core/js/src/common/components/ModalManager.tsx
> +        <div className="ModalManager modal" modal-key={modal.key} style={{ zIndex }}>
We should also add `aria-hidden="true"` to all models except the active one.

Also `role="dialog"`.

2022-06-15 18:57 UTC, jaspervriends commented
Thanks for the feedback, will work on it later this week

2022-06-26 14:57 UTC, jaspervriends commented
Processed feedback :)

2022-07-11 07:40 UTC, davwheat submitted a review, later dismissed
I've addressed some things with commits on this PR, but would like a sanity check for my changes from another core dev before looking to merge this.

Thank you for your work on this! This is a big improvement for Flarum's modals system! :)

2022-07-11 12:42 UTC, SychO9 requested changes, later dismissed
Code looks good! a few comments and a bug I noticed. Thanks a lot for the PR!

There's an issue with the scrolling behavior, I think a video will better explain it:
https://user-images.githubusercontent.com/20267363/178266180-69aaa829-b528-4808-999f-4693bd15b3a5.mp4

2022-07-11 12:42 UTC, SychO9 commented on framework/core/js/src/forum/components/LogInModal.tsx
> +    app.modal.show(ForgotPasswordModal, attrs, true);
I don't believe this should be stackable 🤔

2022-07-11 12:42 UTC, SychO9 commented on framework/core/less/common/Modal.less
>    overflow: hidden;
`.modal-open` definition is dead code now I think

2022-07-11 12:42 UTC, SychO9 commented on framework/core/js/src/common/states/ModalManagerState.ts
> +  show(componentClass: UnsafeModalClass, attrs?: Record<string, unknown>): void;
in 2.0 we'll probably keep the new `stackModal` argument set to `false` by default (or `true`). So I think we could dro this signature and the deprecation mark. Thoughts?

2022-07-14 11:03 UTC, davwheat commented on framework/core/js/src/forum/components/LogInModal.tsx
> +    app.modal.show(ForgotPasswordModal, attrs, true);
Sorry, was using this for testing! 🙈

2022-07-14 11:10 UTC, davwheat commented
oops

2022-07-14 13:11 UTC, davwheat commented
RE the scrolling bug: isn't this how the modals currently work in core?

https://user-images.githubusercontent.com/7406822/178990288-fede20f7-ccbc-4bf0-a72f-979446491969.mp4

2022-07-14 13:14 UTC, SychO9 commented
yea but that isn't how they work in this branch 🙈 `0:15` of my uploaded video shows behavior in this branch

2022-07-14 13:36 UTC, davwheat commented
OH I didn't watch for long enough! Right, I'll get on that.

2022-07-14 14:53 UTC, davwheat commented
@SychO9 Fixed, I hope.

2022-07-15 14:03 UTC, SychO9 commented
🙈 now you can't scroll inside a modal

2022-07-26 10:20 UTC, SychO9 reviewed
Using one backdrop seems great! I think only small tweaks are left.

2022-07-26 10:20 UTC, SychO9 commented on framework/core/less/common/Modal.less
> +  pointer-events: none;
so the scrollbar shows up correctly but with `pointer-events: none` I can't scroll. But removing this also means you can't click outside to close 🤔

2022-07-26 10:20 UTC, SychO9 commented on framework/core/js/src/common/components/ModalManager.tsx
> +            data-showing={!!this.attrs.state.modalList.length}
Ideally, the backdrop would show behind the latest open modal and above the others. I think a simple CSS trick would do it: (other comment below for follow up)

```suggestion
            data-showing={!!this.attrs.state.modalList.length}
            style={{'--modal-count': this.attrs.state.modalList.length}}
```

2022-07-26 10:20 UTC, SychO9 commented on framework/core/less/common/Modal.less
> +  z-index: ~"calc(var(--zindex-modal) - 1)";
```suggestion
  z-index: ~"calc(var(--zindex-modal) + var(--modal-count)) - 2";
```

2022-07-29 09:12 UTC, luceos commented
The patience in this PR is admirable.

2022-07-31 13:27 UTC, davwheat commented
PS: JS checks fail due to attempting to commit and push dist JS to Jasper's repo since the PR is based on the `main` branch.

2022-08-05 15:52 UTC, SychO9 commented
Under known issues: https://caniuse.com/pointer-events
> Moving the scrollbar on an object with pointer-events: none; works in Firefox, but doesn't work in either Chrome or IE.

What I did is introduce invisible backdrops under each modal so that we don't have to use `pointer-events` and be able to easily exit the modal while maintaining scrollabilty (*is that a word?*).

2022-08-05 16:18 UTC, davwheat commented
Ahhhh that's a great find!

I didn't think of that idea and don't think I ever would have!

2022-08-05 18:14 UTC, SychO9 commented on framework/core/js/src/common/components/ModalManager.tsx
> +  protected handlePossibleBackdropClick(e: MouseEvent | TouchEvent): void {
```suggestion
  protected handlePossibleBackdropClick(e: MouseEvent): void {
```

2022-08-08 12:25 UTC, davwheat approved these changes

2022-08-08 12:27 UTC, davwheat commented
Rebased on `main`.

2022-08-08 12:28 UTC, SychO9 approved these changes

2022-08-08 12:29 UTC, merged

2022-08-08 12:29 UTC, davwheat commented
phew that was a big one 😄