perf(statistics): split timed data into per-model XHR requests
flarum/framework pull request #3601
Opened 2022-08-15 02:21 UTC by davwheat

**Changes proposed in this pull request:**

- splits up timed data into multiple XHR requests so info about the models are loaded separately
- also kills off the timezone offset option that was undocumented and seemingly not useful

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

2022-08-15 10:34 UTC, luceos approved these changes

2022-08-16 16:47 UTC, SychO9 requested changes
While the `flarum-statistics.timezone` setting doesn't seem to actually be a thing, I don't think we want to remove the rest of the conversion to user timezone.

2022-08-16 16:51 UTC, davwheat commented
From my understanding, the code gets the user timezone in PHP (`date_default_timezone_get`), which should always be UTC for Flarum, right?

2022-08-16 17:02 UTC, SychO9 commented
you're right, all of the conversion relies on that value, which is essentially the server default anyway.

2022-08-16 17:02 UTC, SychO9 approved these changes

2022-08-16 17:30 UTC, merged