feat: contrast util with yiq calculator
flarum/framework pull request #3652
Opened 2022-09-25 16:26 UTC by Ornanovitch

**Needed for #3633**

**Changes proposed in this pull request:**

The `getContrast` utility converts a hex color to rgb, and then calcul a YIQ value in order to get the appropriate contrast value (is it dark or is it light?)

See https://www.w3.org/TR/AERT/#color-contrast for references

**Reviewers should focus on:**

I don't know... Is the name getContrast ok regarding your naming conventions?

**Screenshot**

tbd

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [x] Tests are not appropriate here.

2022-09-26 08:21 UTC, davwheat requested changes
Ooh, you moved this here! Makes sense.

I left a comment about exporting an `isDark` util so we don't need to compare against 128 in our code in your draft PR. Could we do that here?

2022-09-26 09:40 UTC, Ornanovitch commented
> I left a comment about exporting an `isDark` util so we don't need to compare against 128 in our code in your draft PR. Could we do that here?

You're right! I'll do it asap :)

2022-09-26 11:24 UTC, Ornanovitch commented
@davwheat It seems a lot better, thanks for your advice!

2022-10-21 12:52 UTC, davwheat approved these changes

2022-10-21 13:02 UTC, davwheat commented on framework/core/js/src/common/utils/isDark.ts
> +
```suggestion
```

2022-10-21 13:02 UTC, davwheat commented on framework/core/js/src/common/utils/isDark.ts
> +  var hexnumbers = hexcolor.replace("#", "");
```suggestion
  let hexnumbers = hexcolor.replace("#", "");
```

2022-11-07 11:19 UTC, imorland approved these changes

2022-11-07 11:20 UTC, merged

2022-11-07 11:24 UTC, Ornanovitch commented
:)

2023-03-16 14:18 UTC, iPurpl3x commented
@Ornanovitch, @imorland, @davwheat `isDark` throws an error and the app crashes if a color is set to `NULL` in the database…

2023-03-16 14:29 UTC, SychO9 commented
please open a bug report with specifics.

2023-03-16 14:53 UTC, iPurpl3x commented
Here you go @SychO9 https://github.com/flarum/framework/issues/3764