feat: allow push additional items to the end of the poststream
flarum/framework pull request #3691
Opened 2022-11-22 11:37 UTC by imorland

**Fixes #0000**

**Changes proposed in this pull request:**
Adds an opportunity for extensions to add additional components via an `ItemList` at the end of the `PostStream`

**Reviewers should focus on:**

**Screenshot**

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2022-11-22 11:51 UTC, davwheat requested changes

2022-11-22 11:51 UTC, davwheat commented on framework/core/js/src/forum/components/PostStream.js
> +  endItems() {
```suggestion
  /**
    * @returns {ItemList<import('mithril').Children>}
    */
  endItems() {
```

2022-11-22 11:54 UTC, davwheat requested changes

2022-11-22 11:54 UTC, davwheat commented on framework/core/js/src/forum/components/PostStream.js
> +      }
I think we could simplify it to this

```suggestion
    if (viewingEnd) {
      items.push(...this.endItems().toArray());
```

2022-11-22 12:11 UTC, imorland commented on framework/core/js/src/forum/components/PostStream.js
> +      }
Thx! :)

2022-11-25 04:40 UTC, davwheat approved these changes

2022-11-25 10:40 UTC, SychO9 approved these changes

2022-11-25 10:59 UTC, merged