Fix bug when infinite scroll was not initialised for notifications dropdown on big screens
flarum/framework pull request #3733
Opened 2023-02-11 22:40 UTC by rob006

**Changes proposed in this pull request:**

On QHD screens `70vh` is bigger than space taken by 10 notifications. As a result there is no scroll for this dropdown, and as a result infinite scroll do not work in this place. I mentioned this on Discord a few months ago: https://discord.com/channels/360670804914208769/707030467450372166/1010096800511836261

This PR sets max height of this dropdown to 800px and increases number of notifications loaded in this dropdown, to make sure it is always filled.

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2023-02-12 00:32 UTC, iamdarkle commented
Coincidentally, I experienced this for the first time last week, and it was on a 1080p screen, in a particular case where the whole list of notifications were from the same discussion.

2023-04-16 19:39 UTC, askvortsov1 requested changes
The max-height change makes sense, but I'm hesitant to remove pagination-by-default from the notifications list controller like that. Couldn't that be a frontend change, with a different `limit` query param depending on screen size?

2023-04-16 20:26 UTC, rob006 commented
> but I'm hesitant to remove pagination-by-default from the notifications list controller like that

This PR does not remove pagination, it changes page size from 10 to 20 items (this is default size from [AbstractSerializeController](https://github.com/flarum/framework/blob/1200c1f72f4feaa3c9a0054213c5930657c738f2/framework/core/src/Api/Controller/AbstractSerializeController.php#L60)).

2023-04-16 20:32 UTC, SychO9 commented
rather than 20, 12 should be enough for this case? notifications listing performance is still not great, so ideally we should avoid doubling items per page.

2023-04-16 21:10 UTC, rob006 commented
12 will not be enough in some cases. I have many notifications like this:

![c7afa43a](https://user-images.githubusercontent.com/5972388/232341929-84f3a111-3df2-404d-a045-02a433fc5d46.png)

In this scenario you need ate least 14-15 notifications to fill 800px of dropdown. And probably there could be cases when you have 4 notifications grouped like this - then you need even more notifications. 20 is just safe value, and performance is not terrible in my case (it is faster than discussions list or single discussion view in most cases).

2023-04-17 00:19 UTC, askvortsov1 approved these changes
I think this all seems reasonable. I don't see why notifications should have a special case for the default limit.

2023-04-17 07:56 UTC, SychO9 approved these changes
> In this scenario you need ate least 14-15 notifications to fill 800px of dropdown. 

Alright then

2023-04-17 08:07 UTC, merged