chore: make WelcomeHero extensible
flarum/framework pull request #3848
Opened 2023-06-28 18:29 UTC by imorland

Construct the `WelcomeHero` component using `ItemList`s so that 3rd party extensions may better customize the component

2023-06-29 16:23 UTC, luceos requested changes
I don't think distinguishing between title and subtitle items makes sense. For instance if you want a p on top of a h1 you will incorrectly assign the p to the title items.

I think one items list would be enough? That's why ItemList has priority?

2023-06-29 17:40 UTC, SychO9 commented
I agree with the above, considering we're just stacking the two lists, one list would be enough and more flexible.

2023-06-29 17:59 UTC, imorland commented
Agreed, two is overkill. I will revise

2023-07-27 10:26 UTC, SychO9 approved these changes

2023-07-27 10:27 UTC, merged