feat: extension bisect
flarum/framework pull request #3980
Opened 2024-04-14 11:39 UTC by SychO9

**Fixes #0000**

**Changes proposed in this pull request:**
https://discuss.flarum.org/d/32734-extension-bisect-utility

**Screenshot**
![image](https://github.com/flarum/framework/assets/20267363/863f7042-ee4f-4de5-9bfd-41ab391095cd)
![image](https://github.com/flarum/framework/assets/20267363/83d88ad7-8c5d-4d2b-96ad-e530787c2990)
![image](https://github.com/flarum/framework/assets/20267363/b9132673-395e-4072-a56d-f95a92edd506)
![image](https://github.com/flarum/framework/assets/20267363/61fa548e-641b-424e-9ab7-793cec9fcc46)
![image](https://github.com/flarum/framework/assets/20267363/33308914-fa7b-4e3a-ac1e-78e3eff06287)
![image](https://github.com/flarum/framework/assets/20267363/c9e48799-e9c6-4995-8eda-6cc81a8f2d58)
![image](https://github.com/flarum/framework/assets/20267363/908cc83b-6e48-40c3-9067-e2abdfb2cebf)
![image](https://github.com/flarum/framework/assets/20267363/dbcec239-ce05-40bb-a0ef-33b1f84c0ead)

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2024-04-14 16:14 UTC, askvortsov1 requested changes
Should there be a way to stop the bisect halfway through?

2024-04-14 16:14 UTC, askvortsov1 commented on framework/core/js/src/admin/components/AdvancedPage.tsx
> +  modalThroughUrlShown = false;
```suggestion
  urlRequestedModalHasBeenShown = false;
```

2024-04-14 16:14 UTC, askvortsov1 commented on framework/core/js/src/admin/components/AdvancedPage.tsx
> +              disabled={app.data.maintenanceMode && app.data.maintenanceMode !== MaintenanceMode.LOW_MAINTENANCE}
I wish we had a way to show a "disabled tooltip"

2024-04-14 16:14 UTC, askvortsov1 commented on framework/core/locale/core.yml
> +          help: Helps to identify the extension causing an issue you observed. This automatically puts the forum in maintenance mode (low) until the process is over.
```suggestion
          help: Helps to identify the extension causing some issue you observed. This automatically puts the forum in maintenance mode (low) until the process is over.
```

2024-04-14 16:14 UTC, askvortsov1 commented on framework/core/locale/core.yml
> +            Forum is no longer in maintenance mode. Extension bisect is over. Based on the information in each step, the cause of the issue is the following extension:
```suggestion
            Forum is no longer in maintenance mode. Extension bisect is over. Based on your responses to each step, the cause of the issue is the following extension:
```

2024-04-14 16:14 UTC, askvortsov1 commented on framework/core/src/Extension/Bisect.php
> +    protected bool $break = false;
Could you add a comment explaining that `break` is present for when we will be running the bisecter across multiple instances of processes (i.e. requests), if that's a correct understanding of why we need it?

2024-04-16 10:18 UTC, SychO9 commented
![image](https://github.com/flarum/framework/assets/20267363/bdf64dde-d97e-498f-85d4-1df97820157d)
![image](https://github.com/flarum/framework/assets/20267363/2b9a7517-0dcb-4895-ac28-11c3e812e0e7)

2024-05-01 16:48 UTC, askvortsov1 approved these changes
Awesome, very exciting!

2024-05-03 13:20 UTC, merged